
target_list: $bed_path

dir: $path_to_local_github_dir

ref_genome: $ref_genome

datasets: $dataset1 $dataset2

#${dataset}.txt in dir, with list of bams

softwares: bcftools gatk freebayes graphtyper

#bcftools or gatk or freebayes or graphtyper

options:
  freebayes: "--min-mapping-quality 30 --min-base-quality 30"
  graphtyper: "--force_no_copy_reference"
  bcftools: "-a DP -Ou --min-MQ 30 --min-BQ 30" #-a DP -Ou IMPERATIVE FOR CALCULATE STATS FOR bcftools
  gatk_HaplotypeCaller: " --java-options -Xmx4000m --minimum-mapping-quality 30 --min-base-quality-score 30"
  gatk_CombineGVCFs: " --java-options -Xmx16000m"
  gatk_GenotypeGVCFs: "--java-options -Xmx16000m"
  sub_sample_vcf_for_stats: "1"

comparissons: all

#None or datasets or softwares or all
